apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app-example
      service: log-message-processor
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: log-message-processor
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v1/spans
          
        image: cloud2help/cicd-projects:lmp
        name: log-message-processor
        imagePullPolicy: Always
      restartPolicy: Always
